project:
  type: book
  output-dir: "docs"

lang: es

book:
  title: "Bitácoras Grupo #5, CA-204 (II-2024)"
  author: "Jeikel Navarro Solis, Gabriel Valverde, Erick Venegas"
  date: today
  site-url: google.com # Vacío por el momento
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - "index.qmd"
    - "bitacora_1.qmd"

bibliography: references.bib
cite-method: citeproc  # Indica que use citeproc para procesar las citas


format:
  html:
      # Pueden usar cualquier tema de los que están aca:
      # https://quarto.org/docs/output-formats/html-themes.html a excepción de
      # los oscuros porque no entiende nada.
    theme: cosmo
    toc: true          # Activa la TOC para HTML
    
  pdf:
    toc: true          # Activa la TOC para PDF
    documentclass: scrreprt
    
execute:
  freeze: auto
  cache: true

from: markdown+tex_math_single_backslash+emoji
link-external-newwindow: true