project:
  type: book
  output-dir: "docs"

lang: es

book:
  title: "Bitácoras Grupo #5, CA-204 (II-2024)"
  author: "Jeikel Navarro Solis, Gabriel Valverde, Erick Venegas"
  date: today
  site-url: google.com # Vacío por el momento
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - "index.qmd"
    - "bitacora_1.qmd"

#bibliography: references.bib

format:
  html:
      # Pueden usar cualquier tema de los que están aca:
      # https://quarto.org/docs/output-formats/html-themes.html a excepción de
      # los oscuros porque no entiende nada.
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
  cache: true

from: markdown+tex_math_single_backslash+emoji
link-external-newwindow: true