#Anexos

## Anexo 1 (CHANGELOG Bitacora 1)

### Chore

- Agrega archivo configuracion pre-commit
- Agrega configuracion repo-actions
- Agrega cambios en docs/
- Modifica la carpeta docs
- Modifica la carpeta docs
- Modifica la carpeta docs

### Feat

- Agrega documentos para quarto
- Agrega carpeta docs
- Agrego la base de datos en formato csv
- Agrego la base de datos en formato txt a manera de respaldo del archivo en formato csv. Cualquier cambio realizado al archivo original sera realizado en este tambien.
- Agrega documentos Bitacora_1
- Agrega comentario en Bitacora_1
- Elimina la base de datos
- Agrega la base de datos
- Agrega la definición de la idea
- Agrega en bitácora 1 identificación de tensiones
- Agrega en bitácora 1, identificación de Tensiones
- Agrega en bitácora 1, Reformulación de la idea en modo pregunta
- Agrega en bitácora 1, argumentación de las preguntas
- Agrega en bitácora 1, argumentación a través de datos
- Agrega en Bitacora 1 avance de revisión bibliografica
- Agrega en bitácora 1, parte de escritura
- Agrega el archivo de references.bib
- Agrega las referencias bibliograficas
- Agrega en bitacora 1 principios y teorias
- Agrega en bitacora 1 busqueda bibliografica
- Agrega la introduccion
- Se agrega a bitácora 1, la UVE de Gowin
- Agrega imagen de la V de Gowin

### Fix

- Arregla una funcionalidad de .gitignore
- Corrige la numeración de la bitacora 1
- Arreglo de index
- Realiza correciones diversas en los documentos
- Corrige error ortografico

## Anexo 2 (Participacion Bitacora 1)

 project     : Bitacora-Grupo-5-CA-0204-II-2024-
 repo age    : 7 days 
 branch:     : main
 last active : 40 minutes ago
 active on   : 4 days
 commits     : 36
 files       : 41
 uncommitted : 10
 authors     : 
    26	Jeikel Navarro  72.2%
     8	Erick Venegas   22.2%
     2	Gara            5.6%