# Apendice

## Correcciones Bitácora 1

La correccion más relevantes se detalla a continuación:

* **Corrección 1:**
Se ha modificado la sección de definición de la idea para ajustarnos mejor a lo que se espera ser observado en la misma. Tal que, nos centramos más en definir claramente la idea de investigación, sin entrar en los detalles ni en dar el paso a paso de cómo se lleva la misma acabo. Por lo que, en esta sección, solo nos limitamos a exponer qué es lo que buscamos investigar y por qué es importante o relevante, dejando los aspectos metodológicos y el desarrollo de este para otras secciones.


## Sugerencias Bitácora 1

A partir del foro consideramos todas las sugerencias:

1. *El grupo podría ser más explícito en la metodología que usará y como abordará el objetivo general, esto lo observé en la sección de principios y teorías donde me parece que no tienen muy claro una teoría con la cual construir ideas relacionadas a la investigación. Hacen un buen análisis de la relación del tema de Riesgos con la Probabilidad y algunas teorías de valoración de riesgos financieros, pero podrían ser más explícitos en cual usarán y como la usarán.*
 - **Respuesta:** Gracias por la observación. Trataremos de que la metodología a utilizar quede un poco más explícita en la sección de principios y teorías, especialmente en relación con el análisis de la valoración de riesgos.  


2. *Es crucial asegurar la validez de los datos utilizados, ya que estos deben reflejar con precisión las características reales de las personas con calificación crediticia. Aunque el enfoque del trabajo esté en el uso de herramientas de análisis de datos, es fundamental que la base de datos sea coherente con la realidad, dado que las conclusiones dependerán de la calidad de la información analizada. Además, sería recomendable incluir un título claro y descriptivo que refleje el objetivo principal del análisis.*
 - **Respuesta:** Agradecemos la sugerencia. Creemos que la base de datos que hemos escogido tiene una gran calidad o por lo menos visto desde un punto de vista académico, ya que está respaldada por el Instituto Tecnológico de Massachusetts (MIT). Adicional a eso, también hemos hecho una limpie de la base de datos para tratar de asegurarnos de aquellos datos tengan cierto grado de validez.  A su vez, también hemos dejado mas en claro el título de la investigación.


3. *Considero que el proceso de selección de la pregunta final se pudo haber beneficiado de una argumentación más detallada para cada una de las opciones preliminares, especialmente haciendo una distinción más explícita entre los factores lógicos, éticos y emocionales que respaldan o cuestionan cada posible interrogante. Asimismo, es posible que la parte final de esta bitácora se pueda enriquecer con una mayor diversidad de fuentes, lo que ofrecería una perspectiva más amplia sobre los estudios que se han realizado previamente sobre el tema.*  
- **Respuesta:** Se tomará en cuenta su comentario. A la vez, estamos de acuerdo en que tal vez no llegamos a abarcar una gran variedad de fuentes, pero esto es debido a que la investigación se quiere mantener lo más aterrizada posible, de manera que no haya fuentes que sean innecesarias que a lo largo del trabajo no lleguen a tener relevancia. No obstante, hemos decido ampliar un poco más las fuentes, manteniendo el principio de no meter fuentes innecesarias. 




4. *Sentí que la bitácora les quedó muy corta, la leí en poco tiempo y no entendí muy bien a qué querían llegar con los objetivos planteados. También siento que les faltó un poco más de referencias. La ventaja es que gracias a la naturaleza del tema esto se puede mejorar bastante fácil en las siguientes bitácoras.*
- **Respuesta:** Agradecemos sus comentarios. A lo largo de la segunda bitácora vamos a profundizar más en los objetivos planteados, además, talvez la extensión de la primer bitácora se optó que fuese lo más concisa posible, tratando de que quedase lo más claro posible lo planteado en la misma, talque no se llegara a caer en redundancias. También como se menciona en otro comentario añadiremos más referencias que sean de utilidad para respaldar mejor el análisis. 

